config/routes.rb
Rails.application.routes.draw do
  get 'creaters/index'
  get 'creaters/new'
  get 'creaters/create'
  get 'creaters/destroy'
  resources :resumes, only: [:new, :create, :index, :destroy]
  resources :sessions, only: [:create,:new, :index, :destroy]
  get 'login', to: 'resumes#index', as: 'login'
 # post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :articles

   resources :creaters, only: [:index, :new, :create, :destroy]
   root "creaters#index"
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	 validates :title, presence: true,
                    length: { minimum: 1 }
      validates :text, presence: true,
                    length: { minimum: 20 }
end

app/models/creater.rb
class Creater < ApplicationRecord
	   mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
       validates :name, presence: true #
end

app/models/resume.rb
class Resume < ApplicationRecord
     mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
    validates :name, presence: true 
     validates :position, presence: true
    validates :attachment, presence: true
    validates :emailId, format: { with: URI::MailTo::EMAIL_REGEXP } # Make sure the owner's name is present.
end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
#  protect_from_forgery with: :exception
protect_from_forgery with: :exception

helper_method :current_user, :logged_in?

def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
end
def logged_in?
	!!current_user
end
def  require_user

	if !logged_in?
		flash[:danger]="you must be logged in"
		redirect_to new_session_path
   else

    flash[:danger]="you must be logged in"
		redirect_to index_session_path
     end
 end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
       redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/channels/application_cable/channel.rb
module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end

app/controllers/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
  end
end

app/controllers/creaters_controller.rb
class CreatersController < ApplicationController
 
   def index
      @creater = Creater.all
   end
   
   def new
      @creater = Creater.new
   end
   
   def create
      @creater = Creater.new(creater_params)
      
      if @creater.save
         redirect_to creaters_path, notice: "The File #{@creater.name} has been uploaded."
      else
         render "new"
      end
      
   end
   
   def destroy
       @creater = Creater.find(params[:id])
        @creater.destroy
      redirect_to creaters_path, notice:  "The File #{creater.name} has been deleted."
   end
   
   private
      def creater_params
      params.require(:creater).permit(:name, :attachment)
   end
   
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
   def index
      @resume = Resume.all
  end 
   def new
      @resume = Resume.new
   end
   
   def create
     
      @resume = Resume.new(resume_params)
      
      if @resume.save
         redirect_to root_path, notice: "The resume #{@resume.name} has been uploaded."
      
      else
         render "new"
      end
      
   end

   private
      def resume_params
      params.require(:resume).permit(:name, :position, :emailId, :attachment)
   end
end
 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #  @session = Session.new   
  
  end
  def index
  
  end
 def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
     redirect_to login_path
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
   session[:user_id]=nil
     redirect_to root_path
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/creaters_helper.rb
module CreatersHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_form.html.erb
<%=bootstrap_form_with scope: :article, url: articles_path, local: true do |f| %>
       <%= f.text_field :title%>
  <br>
    <%= f.text_area :text%>
  <br>
    <%=f.submit%>
<% end %>

app/views/articles/edit.html.erb
<h3>Edit</h3>
<%= render 'form' %>
<%= link_to 'Article page', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<br>
<br>
<table class = "table table-bordered table-striped">
  <tr>
    <th>Title</th>
    <th>Text</th>
   
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
  
      <td><%= link_to 'Edit', edit_article_path(article) %></td>

      <td><%= button_to 'Destroy', article_path(article), method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<%= render 'form' %>
<%= link_to 'Article page', articles_path %>
 

app/views/articles/show.html.erb
<h3>Show</h3>
	<br>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<%= link_to 'Article page', articles_path %>

app/views/creaters/create.html.erb
<h1>Creaters#create</h1>
<p>Find me in app/views/creaters/create.html.erb</p>

app/views/creaters/destroy.html.erb
<h1>Creaters#destroy</h1>
<p>Find me in app/views/creaters/destroy.html.erb</p>

app/views/creaters/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "New File", new_creater_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @creater.each do |c| %>
         
         <tr>
            <td><%= c.name %></td>
            <td><%= link_to "Download File", c.attachment_url %></td>
            <td><%= button_to "Delete File",c, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{c.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/creaters/new.html.erb
<h2> File Uploader</h2>
<br>
<% if !@creater.errors.empty? %>
   <div class = "alert alert-error">
      
      <ul>
         <% @resume.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
         <% end %>
      </ul>
      
   </div>
<% end %>

   <%=bootstrap_form_for @creater, html: { multipart: true } do |f| %>
      <%= f.text_field :name,label: "name"  %>
      <%= f.file_field :attachment,label:"attachment" %>
      <%= f.submit "Save", class: "btn btn-primary" %>
   <% end %>

app/views/layouts/_navigation.html.erb
    <!-- <h2><font color="white">SR#</font><font color="Lightgreen">tech</font><font color="white">career</font></h2><br>
-->  

app/views/layouts/application.html.erb
<html>


<head>
  <title>srtech</title>
<%= stylesheet_link_tag 'application', media: "all", "data-turbolinks-track" => true %>
 </head>
<body> 
<%= yield %>
   

<body>
</html>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>delet<h1>

app/views/resumes/index.html.erb
<div class=hole><h3><%=image_tag ("res/f.svg")%>&nbsp;SR#</font><font color="Lightgreen">tech</font> Candidates</h3></div>
<div class=i1><%=link_to "Log out", logout_path,method: :delete,class: "btn btn-primary" %></div>
</br>
</br>
</br>
<br>
<%= image_tag ("res/hr.svg")%>
<div class=indexline> 
</font><font color=#B5B4B4>
  <h3><p>“Nothing we do is more important than hiring and developing </p>
  <p>  people. At the end of the day, you bet on people,</p>
        <p>  not on strategies."</p></h3>
      </div></font>
<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th>
         <th>Position</th>
         <th>EmailId</th>
         <th>Resume</th>
        
      </tr>
   </thead>
   
   <tbody>
      <%@resume.each do |resume| %>
         <tr>
              <td><%= resume.name %></td>
             <td><%= resume.position %></td>
              <td><%= resume.emailId %></td>
            <td><%= link_to "View Resume", resume.attachment_url%></td>
                
         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/resumes/new.html.erb
<div class=hole><h3><%=image_tag ("res/f.svg")%>&nbsp;SR#</font><font color="Lightgreen">tech</font> career</h3></div>
<h4><div class=s><p><%=link_to"Home", class: "a-primary"%></p></div>
<div class=s0><%=link_to"Product"%></div>
<div class=s1><%=link_to"Career",new_resume_path%></div>
<div class=s2><%=link_to "Recruiter",new_session_path%></div>
<div class=s3><%=link_to"Contact"%></div>
</h4>
<br>
<br>
<div class=f><p><h2>Want to join us for a game?</h2></p></div> 
<%=image_tag ("res/home-banner.svg")%>
<br>
<br
<p><h3><center>Careers At SRtech</center></h3></p>
<p><center>At SRtech, we pride ourselves on building powerful, sophisticated software that’s fun and easy to use. We<br>
believe that customers are the foundation of a successful business and we want to enable every team to deliver<br> moments of wow to them.
<br>
<br>
We are constantly on the lookout for smart people who are passionate about building great products, designing <br>great,experiences, building scalable platforms, and making customers happy. If this describes you, feel free to<br> take a look at our openings below and apply!
</p>
</center>
<!--<div class="image"><%= image_tag ("res/r3.jpg")%></div>-->
<div class = "yes">
  <br>
<p><h4>Submit Your Application</font></h4></p>
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

   <%=bootstrap_form_for @resume do |f| %>
      <%= f.text_field :name ,label: "Name"%> 
      <%= f.text_field :position ,label:"Position"%> 
      <%= f.email_field :emailId ,label: "Email"%>
      <%=  f.file_field :attachment, label:"Resume"%>
      <%= f.submit "Submit Application", class: "btn btn-primary"%>
   <% end %>
   
 </div>
<div class="d">
<h3><font color=#0C2875>Why Work Here?</font></h3></p>
</div>

   <div class="t">        
           <p><h3><font color=#0C2875><%= image_tag ("res/environment.svg")%>&nbsp;Environment</p></font></h3>
       
    <br>
              <p>We do our best work when the stress</p>
              <p>is low,the surroundings are inspiring,</p>
               <p> and hierarchy is flat.</p>
          </div>

   <div class="t1">      
          
         <p><h3><font color=#0C2875><%= image_tag ("res/the_team.svg")%>&nbsp;The Team   </p></font></h3>
         <br>

               <p>We’re big mix of engineers,</p>
              <p>creatives, data nerds, and more,</p>
                <p>You can find your place with us.</p>
     
    </div>
   

    <div class="t2">    
                  <p><h3><font color=#0C2875><%= image_tag ("res/learn.svg")%>&nbsp;Learn</font></h3> </p> 
                  <br>

                <p> Don’t just work harder, </p>
                <p> learn and share how become a </p>
                <p> master craftsman at your art. </p>

       </div>      